2020-05-02 19:04:09,952 ERROR: Exception on /translate [POST] [in C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\WORK\FlaskProject\flaskApp\routes.py", line 203, in translate_text
    request.form['dest_language'])})
  File "D:\WORK\FlaskProject\flaskApp\translate.py", line 25, in translate
    print(r.content.decode('utf-8-sig')['text'])
TypeError: string indices must be integers
2020-05-02 19:04:21,123 ERROR: Exception on /translate [POST] [in C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\WORK\FlaskProject\flaskApp\routes.py", line 203, in translate_text
    request.form['dest_language'])})
  File "D:\WORK\FlaskProject\flaskApp\translate.py", line 25, in translate
    print(r.content.decode('utf-8-sig')['text'])
TypeError: string indices must be integers
2020-05-02 19:05:23,093 INFO: Microblog startup [in D:\WORK\FlaskProject\flaskApp\__init__.py:52]
2020-05-02 20:34:31,635 INFO: Microblog startup [in D:\WORK\FlaskProject\flaskApp\__init__.py:52]
2020-05-02 20:36:05,567 INFO: Microblog startup [in D:\WORK\FlaskProject\flaskApp\__init__.py:52]
2020-05-02 20:39:08,641 INFO: Microblog startup [in D:\WORK\FlaskProject\flaskApp\__init__.py:52]
2020-05-02 20:39:49,975 INFO: Microblog startup [in D:\WORK\FlaskProject\flaskApp\__init__.py:52]
2020-05-02 20:39:54,802 ERROR: Exception on /translate [POST] [in C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\WORK\FlaskProject\flaskApp\routes.py", line 203, in translate_text
    request.form['dest_language'])})
  File "D:\WORK\FlaskProject\flaskApp\translate.py", line 26, in translate
    return json.loads(r.content.decode('utf-8-sig')['text'][0])
TypeError: string indices must be integers
2020-05-02 20:40:42,524 INFO: Microblog startup [in D:\WORK\FlaskProject\flaskApp\__init__.py:52]
2020-05-02 20:40:50,158 ERROR: Exception on /translate [POST] [in C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\ankit\anaconda3\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\WORK\FlaskProject\flaskApp\routes.py", line 203, in translate_text
    request.form['dest_language'])})
  File "D:\WORK\FlaskProject\flaskApp\translate.py", line 26, in translate
    return json.loads(r.content.decode('utf-8-sig')['text'])
TypeError: string indices must be integers
2020-05-02 20:42:21,146 INFO: Microblog startup [in D:\WORK\FlaskProject\flaskApp\__init__.py:52]
2020-05-02 20:44:06,617 INFO: Microblog startup [in D:\WORK\FlaskProject\flaskApp\__init__.py:52]
2020-05-02 20:44:32,225 INFO: Microblog startup [in D:\WORK\FlaskProject\flaskApp\__init__.py:52]
